### ISSUE TITLE
:direction: "alternate" does not work

### ISSUE THREAD

**Issue by MarcusTutorials** [megasanjay/vue3-lottie#3]
First, thanks for this npm package. It save a lot of time ;)
My lottie files runs fine, but it does not reverse after finished and it shows up this error message in the console. 🤔

![image](https://user-images.githubusercontent.com/26997041/153176372-1b1e71d8-9ad4-4e6b-9367-44bb4ccf16b5.png)

Here my Code:  
![Vue3_LottieLoop](https://user-images.githubusercontent.com/26997041/153175699-63b1a074-f4a9-4879-bd4e-aa9815380cd4.png)

I was reference it from the docs. 
![image](https://user-images.githubusercontent.com/26997041/153177727-99678857-0217-43ec-b76e-0e80d8d7e2fd.png)

Do I made something wrong or is it a bug? 😅

**Comment by megasanjay** [comment]
Thank you for using the library. So your issue is `:direction`. What you need to be using for the attribute name is either `direction="alternate"` or something like `:direction="'alternate'"`. If you use the **:** before the attribute name, vue is expecting to see a js variable, and not a string (unless you add with a clear string format). Remove the `:` and it should work for you :)

**Comment by MarcusTutorials** [comment]
@megasanjay 
Oh. I didn't notice it xD
Now it works. Thanks for the help :)
