### ISSUE TITLE
Whether the animationData property is reactive when using the component in vue3

### ISSUE THREAD

**Issue by HighSky2GT** [megasanjay/vue3-lottie#400]
```Vue
<script setup lang="ts">
import { ref } from 'vue'
import { Vue3Lottie } from 'vue3-lottie'
import AstronautJSON from './astronaut.json'
import AstronautJSON2 from './astronaut2.json'
const data = ref(AstronautJSON)
function change(){
  // The data has changed, but Vue3Lottie will not run again
  data.value = AstronautJSON2
}
</script>

<template>
  <Vue3Lottie :animationData="AstronautJSON" :height="200" :width="200" />
  <button @click="change">change</button>
</template>
```
# expect
animationData or animationLink property is reactive

**Comment by megasanjay** [comment]
This is intentional. Having the animation data update dynamically would cause many issues with the event listeners for the lottie-web library. This would also require me to destroy and reset all the custom loop timings to ensure everything plays as intended. 

I would suggest rerendering the component after removing it, using the `key` prop, or having both present and show and hiding the correct one based on some conditions.

**Comment by megasanjay** [comment]
Thank you for the PR. This is marked as complete in v3.2.0
